version: '3'
services:
  web:
    build: .
    ports:
      - "20011:3000"
    links:
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_USER_PRINCIPLE_NAME: ${NEXT_PUBLIC_USER_PRINCIPLE_NAME}
      KV_PREFIX: ${KV_PREFIX}
      REDIS_URL: ${REDIS_URL}
      MS_CLIENT_ID: ${MS_CLIENT_ID}
      MS_CLIENT_SECRET: ${MS_CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
  redis:
    image: redis
